spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tdsn?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      hibernate:
        ddl-auto: create-drop
  redis:
    host: localhsot
    port: 6379
